version: "2.3"

services:
    uservice-dynconf:
        image: ghcr.io/userver-framework/docker-userver-build-base:release
        privileged: true
        network_mode: bridge
        environment:
          - BUILD_DIR=${BUILD_DIR:-/build}
          - BUILD_TYPE=${BUILD_TYPE:-Release}
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        volumes:
          - .:/uservice-dynconf:rw
          - ./third_party/userver/tools/docker:/tools:ro
          - ${CCACHE_DIR:-~/.ccache}:/ccache:rw
          - ${TC_CORES_DIR:-./cores}:/cores:rw
        ports:
          - 8083:8083
        working_dir: /uservice-dynconf
        entrypoint:
          - /tools/run_as_user.sh
