# yaml
components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4
            thread_name: main-worker

        fs-task-processor: 
            thread_name: fs-worker
            worker_threads: 4

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8083
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        tracer:
            service-name: service_dynamic_configs

        taxi-config:
            fs-cache-path: ''

        taxi-config-fallbacks:
            fallback-path: /etc/service_dynamic_configs/dynamic_config_fallback.json

        manager-controller:
        statistics-storage:
        auth-checker-settings:

        dns-client:
            fs-task-processor: fs-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-configs-values:
            path: /configs/values
            method: POST
            task_processor: main-task-processor

        handler-admin-v1-configs:
            path: /admin/v1/configs
            method: POST
            task_processor: main-task-processor

        handler-admin-v1-configs-delete:
            path: /admin/v1/configs/delete
            method: POST
            task_processor: main-task-processor

        testsuite-support: {}

        configs-cache:
            pgcomponent: settings-database
            update-interval: 10s
            full-update-interval: 1m
            update-correction: 2s
            update-jitter: 1s
            chunk-size: 100

        settings-database:
            dbconnection: 'postgresql://testsuite@localhost:15433/service_dynamic_configs_service_dynamic_configs'
            blocking_task_processor: fs-task-processor
            handlers_cmd_ctl_task_data_path_key: http-handler-path      # required for POSTGRES_HANDLERS_COMMAND_CONTROL
            handlers_cmd_ctl_task_data_method_key: http-request-method  # required for POSTGRES_HANDLERS_COMMAND_CONTROL
            dns_resolver: async

        tests-control:
            path: /tests/control
            method: POST
            task_processor: main-task-processor
